apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: helloworldreplica
   labels:
      app: helloworldnew
spec:
   replicas: 4
   selector:
     matchLabels:
       app: helloworldnew
   template:
      metadata:
        labels:
        app: helloworldnew
      spec:
        containers:
            - name: helloreplica
              image: arjunachari12/k8s-demo
              ports:
                - name: replicaport
                  containerPort: 3000
