apiVersion: v1
kind: ReplicationController
metadata:
   name: nginxreplicas
spec:
   replicas: 2
   selector:
      app: nginxapp
   template:
      metadata:
         labels:
            app: nginxapp
      spec:
         containers:
            - name:  nginxcontainer
              image: nginx:latest
              ports:
                 - containerPort: 80
