apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
   labels:
      app: nginxapp
spec:
    containers:
       - name: nginx-container
         image: nginx
         port:
           name: nginx-port
           containerPort: 80
